# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quadratic_calc.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'quadratic_calc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14quadratic_calc.proto\x12\x0equadratic_calc\":\n\x0e\x43omputeRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x02\x12\x0c\n\x04num2\x18\x02 \x01(\x02\x12\x0c\n\x04num3\x18\x03 \x01(\x02\"!\n\x0f\x43omputeResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2b\n\x14quadratic_Calculator\x12J\n\x07\x43ompute\x12\x1e.quadratic_calc.ComputeRequest\x1a\x1f.quadratic_calc.ComputeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quadratic_calc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPUTEREQUEST']._serialized_start=40
  _globals['_COMPUTEREQUEST']._serialized_end=98
  _globals['_COMPUTERESPONSE']._serialized_start=100
  _globals['_COMPUTERESPONSE']._serialized_end=133
  _globals['_QUADRATIC_CALCULATOR']._serialized_start=135
  _globals['_QUADRATIC_CALCULATOR']._serialized_end=233
# @@protoc_insertion_point(module_scope)
